<!DOCTYPE html>
<html>
<head>
  <title>{{.siteName}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="/static/jquery/3.2.1/jquery.min.js"></script>
  <script src="/static/popper.js/1.15.0/umd/popper.min.js"></script>
  <script src="/static/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<!-- 导航栏 -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="./">首页</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/group">分组</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/reload">刷新缓存</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="./about">关于</a>
    </li>
  </ul>
</nav>

<div class="jumbotron text-center">
  <h2>你我相逢，皆是有缘分</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
     <h3>文章列表</h3>
        {{range .topics_l}}
        <ul class="list-group">{{range .Topics}}
        <li class="list-group-item list-group-item-action">[{{.Time.Format "06-01-02"}}] <a href="{{$.domain}}/{{.TopicID}}.html">{{.Title}}</a></li>{{end}}
        </ul>
        {{end}}
    </div>
    <div class="col-sm-6">
      <h3>右侧</h3>
        {{range .topics_r}}
        <ul  class="list-group">{{range .Topics}}
            <li class="list-group-item list-group-item-action">[{{.Time.Format "06-01-02"}}] <a href="{{$.domain}}/{{.TopicID}}.html">{{.Title}}</a></li>{{end}}
        </ul>
        {{end}}
    </div>
  </div>
</div>

<!-- Footer 页脚 -->
<footer class="navbar-fixed-bottom">
<div class="container">
<div class="row">
    <div class="col-lg-12">
    <div style="text-align:center;margin-top:15px;margin-bottom:50px;">
Copyright &copy; jiftle.github.io, generated by gitmdblog, designed by <a href="https://github.com/jiftle/gitmdblog">jiftle</a>. <a href="https://github.com/jiftle/gitmdblog">[source]</a>
</div>
    </div>
    <!-- /.col-lg-12 -->
</div>
</div>
</footer>

</body>
</html>
